version: "3.7"

services:
  database_ormfit:
    image: postgres
    container_name: database_ormfit
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ormfit
      - POSTGRES_DB=ormfit
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: ormfit
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database_ormfit
    depends_on:
      - database_ormfit

volumes:
  pgdata:
    driver: local